### ISSUE TITLE
just hello :）

### ISSUE THREAD

**Issue by aleivc** [joas77/englishLearning#1]
I'm glad to find a repo for English, Git shows that it was updated 11 hours ago. what you want to build it into? maybe i can help you, and it may improve my english.

**Comment by joas77** [comment]
Hi there
This is awesome! I didn't expect to receive help from literally the other side of the planet!
I'm trying to build a web app to help to improve English pronunciation.

The concept at the moment is really simple, a page with an input text where you can type the text
that you want to practice. And a button to start "listen" your voice and compare the text in the box with the text received by a speech recognition module (at the moment only will work on chrome browser). Check attached picture

I want to add the option to automatically fetch a famous quote using https://quotes.rest/ or a similar service.

The speech recognition module is not working properly yet.

If you want to check and play with the code just clone the repo and then cd to
client/english_learning folder and type command `npm start`.
Just consider that it's an early version and are lots of things to fix and add, and I don't have working experience with javascript just small projects.

Any help and suggestions are very welcome.

thanks.

There
![image](https://user-images.githubusercontent.com/4263054/67699890-838aa400-f972-11e9-8dff-e97339defb5d.png)
